version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(github)"
  - package-ecosystem: "npm"
    directory: "/templates/angular"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(templates/angular)"
    groups:
      angular-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/templates/node"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(templates/node)"
    groups:
      node-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/templates/python"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(templates/python)"
    groups:
      python-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/templates/rust"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(templates/rust)"
    groups:
      rust-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/templates/rust-web-server"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(templates/rust-web-server)"
    groups:
      rust-web-server-dependencies:
        patterns:
          - "*"
